# Generated by Django 2.2.5 on 2019-11-07 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ID',
            new_name='threadID',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default='test', max_length=144, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image_description',
            field=models.CharField(default='test', max_length=240),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='image',
            field=models.ImageField(default='test', max_length=144, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='image_description',
            field=models.CharField(default='tests', max_length=240),
        ),
        migrations.AddField(
            model_name='userexpanded',
            name='gameSprite',
            field=models.ImageField(default='test', max_length=144, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='test', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(default='test', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='messagetread',
            name='participants',
        ),
        migrations.AddField(
            model_name='messagetread',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagetread',
            name='threadName',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='message',
            field=models.CharField(default='test', max_length=500),
        ),
    ]
