# Generated by Django 2.2.5 on 2019-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontent',
            old_name='message',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(max_length=144, upload_to='content/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='image',
            field=models.ImageField(max_length=144, upload_to='content/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userexpanded',
            name='gameSprite',
            field=models.ImageField(max_length=144, upload_to='content/spites/%user'),
        ),
    ]
