# Generated by Django 2.2.5 on 2019-12-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191210_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontent',
            old_name='username',
            new_name='author',
        ),
    ]
